version: '3'

services:
  code-server:
    user: root
    build:
      context: .
      dockerfile: ./amd64/Dockerfile
    environment:
      - EUID=1001
      - EGID=1001
    volumes:
      - /home/vscode:/home/vscode
    ports:
      - 8080:8080
    privileged: true
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfine
 rclone:
    image: mumiehub/rclone-mount
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - "/dev/fuse:/dev/fuse"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - "$HOME/.config/rclone/rclone.conf:/config/rclone.conf:ro"
      - "./config.txt:/config/config.txt:ro"
      - "./mounts:/mnt:shared"
